Possibility to use TwistStamped (still Twist by default)
ros-teleop/teleop_tools pull request #54
Opened 2020-08-22 07:59 UTC by klintan

Ros2_control decided to go for TwistStamped (which I can understand because of the extra info + timestamp you get) however that makes it incompatible with this library. This is a suggested fix for that, if you feel this is an option, i'll go ahead and change the other modules (joy and  mouse) the same way.

Let me know what you think :) 

PS. would be good to create a foxy-devel branch as well.

2020-11-03 06:53 UTC, bmagyar commented on key_teleop/key_teleop/key_teleop.py
> +        self._twist_stamp_enabled = self.declare_parameter('twist_stamped_enabled', False).value
```suggestion
        self._publish_stamped_twist = self.declare_parameter('publish_stamped_twist', False).value
```
I'd suggest renaming this variable and the parameter name for making it even clearer

2020-11-03 06:54 UTC, bmagyar commented on key_teleop/key_teleop/key_teleop.py
> +    def _get_twist_stamped(self, linear, angular):
Typically, `getXYZ` is supposed to fetch a value from an object. Here, you are making a new twist stamped object from the arguments, I suggest renaming
```suggestion
    def _make_twist_stamped(self, linear, angular):
```

2020-11-03 06:55 UTC, bmagyar commented on key_teleop/key_teleop/key_teleop.py
> +    def _get_twist_stamped(self, linear, angular):
At the same time, we may as well rename `_get_twist` while at it...

2020-11-03 06:55 UTC, bmagyar requested changes
The changes look good in general, please rebase to latest master & have a look at my comments.

2020-12-08 05:35 UTC, klintan commented
> The changes look good in general, please rebase to latest master & have a look at my comments.

Sorry for the slow response on this one. It should all be addressed now as far as the feedback goes.

2021-01-29 14:57 UTC, Rayman commented
This PR references https://github.com/ros-planning/navigation2/issues/1594. See also the discussion there.

2021-03-21 19:14 UTC, bmagyar approved these changes

2021-03-21 19:14 UTC, merged

2021-03-21 20:02 UTC, Rayman commented
@bmagyar this PR breaks compatibility right? So you might only want this PR for galactic